### ISSUE TITLE
Use the actual app name

### ISSUE THREAD

**Issue by schneelittchen** [schneelittchen/Liddell#4]

**Comment by schneelittchen** [comment]
currently it converts the app name and capitalises it

**Comment by denialpan** [comment]
Should keep it the way that the developers intended their app to be named, therefore, no converting to capitals.

**Comment by schneelittchen** [comment]
no if you make an app called GiveMeBackMyFridge i'll convert it to Givemebackmyfridge @denialpan

**Comment by denialpan** [comment]
Awful way to only capitalize the first letter when the developer intended that each subsequent word be capitalized, especially in possession of my fridge.

**Comment by schneelittchen** [comment]
btw your cheese is great @denialpan @denialpan

**Comment by denialpan** [comment]
get on @schneelittchen

**Comment by EnzoBeth** [comment]
damn what type of cheese do you eat ?

**Comment by schneelittchen** [comment]
was the good kind

**Comment by MrGcGamer** [comment]
Sounds kinda cheesy if you ask me
